import { ThirdPartyOperationResult } from "./external.model";

export interface GeneralApiError {
  timestamp: string;
  type: ErrorType;
}

export interface ValidationApiError extends GeneralApiError {
  fieldErrors: FieldError[];
}

export interface FieldError {
  codes: string[];
  arguments: any[];
  defaultMessage: string;
  objectName: string;
}

export interface SimpleApiError extends GeneralApiError {
  message: string;
}

export interface ExternalServiceApiError extends SimpleApiError {
  externalResult: ThirdPartyOperationResult;
}

export enum ErrorType {
  GENERAL_FIELD_VALIDATION = "GENERAL_FIELD_VALIDATION",
  GENERAL_MISFORMED_REQUEST = "GENERAL_MISFORMED_REQUEST",
  GENERAL_FORBIDDEN = "GENERAL_FORBIDDEN",

  AUTH_GENERAL = "AUTH_GENERAL",
  AUTH_EXPIRED_REFRESH_TOKEN = "AUTH_EXPIRED_REFRESH_TOKEN",
  AUTH_REVOKED_REFRESH_TOKEN = "AUTH_REVOKED_REFRESH_TOKEN",
  AUTH_INVALID_REFRESH_TOKEN = "AUTH_INVALID_REFRESH_TOKEN",
  AUTH_NO_REFRESH_TOKEN = "AUTH_NO_REFRESH_TOKEN",

  PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND",
  PROJECT_INCONSISTENT_DATE = "PROJECT_INCONSISTENT_DATE",
  PROJECT_DROPBOX_CONNECTION_ERROR = "PROJECT_DROPBOX_CONNECTION_ERROR",

  TASK_NOT_FOUND = "TASK_NOT_FOUND",
  TASK_DATE_BEFORE_PROJECT_START = "TASK_DATE_BEFORE_PROJECT_START",
  TASK_DATE_WRONG_INTERVAL = "TASK_DATE_WRONG_INTERVAL",

  LABEL_NOT_FOUND = "LABEL_NOT_FOUND",

  USER_NOT_FOUND = "USER_NOT_FOUND",

  ATTACHMENT_NOT_FOUND = "ATTACHMENT_NOT_FOUND",
  ATTACHMENT_FILE_TOO_LARGE = "ATTACHMENT_FILE_TOO_LARGE",
  ATTACHMENT_UPLOAD_FAILURE = "ATTACHMENT_UPLOAD_FAILURE",
  ATTACHMENT_DOWNLOAD_FAILURE = "ATTACHMENT_DOWNLOAD_FAILURE",
  ATTACHMENT_FILE_DELETE_FAILURE = "ATTACHMENT_FILE_DELETE_FAILURE",

  MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND",
  MESSAGE_COMMENT_NOT_FOUND = "MESSAGE_COMMENT_NOT_FOUND",
  MESSAGE_REPLY_NOT_FOUND = "MESSAGE_REPLY_NOT_FOUND",

  OAUTH2_INTERNAL_FAILURE = "OAUTH2_INTERNAL_FAILURE",
  OAUTH2_EXTERNAL_ID_TAKEN = "OAUTH2_EXTERNAL_ID_TAKEN",
  OAUTH2_ALREADY_AUTHORIZED = "OAUTH2_ALREADY_AUTHORIZED",
  OAUTH2_NO_STATE_FOUND = "OAUTH2_NO_STATE_FOUND",
  OAUTH2_CALLBACK_FAILURE = "OAUTH2_CALLBACK_FAILURE",

  REGISTRATION_USERNAME_TAKEN = "REGISTRATION_USERNAME_TAKEN",
  REGISTRATION_EMAIL_TAKEN = "REGISTRATION_EMAIL_TAKEN",

  EXTERNAL_INTERRUPTED = "EXTERNAL_INTERRUPTED",

  INTERNAL = "INTERNAL"
}
