export enum ValidationBoundaries {
  USER_USERNAME_MAX_LENGTH = 25,
  USER_USERNAME_MIN_LENGTH = 5,
  USER_PASSWORD_MAX_LENGTH = 100,
  USER_PASSWORD_MIN_LENGTH = 8,

  PROJECT_NAME_MAX_LENGTH = 50,
  PROJECT_NAME_MIN_LENGTH = 3,
  PROJECT_DESCRIPTION_MAX_LENGTH = 2000,

  TASK_NAME_MAX_LENGTH = 50,
  TASK_NAME_MIN_LENGTH = 3,
  TASK_DESCRIPTION_MAX_LENGTH = 2000,

  SUBTASK_NAME_MAX_LENGTH = 200,

  LABEL_NAME_MAX_LENGTH = 25,

  MESSAGE_MAX_LENGTH = 2000,
};
